name: mindspend
description: "MindSpend - See what your money really costs"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: any
  firebase_auth: any
  cloud_firestore: any
  google_sign_in: any

  # State Management
  flutter_riverpod: any

  # Navigation
  go_router: any

  # Storage
  shared_preferences: any

  # UI
  google_fonts: any
  cupertino_icons: ^1.0.8
  lucide_icons: any
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
