name: mindspend
description: "MindSpend - See what your money really costs"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  cloud_firestore: ^6.1.2
  google_sign_in: ^7.2.0

  # State Management
  flutter_riverpod: ^3.2.1

  # Navigation
  go_router: ^17.1.0

  # Storage
  shared_preferences: ^2.5.4
  image_picker: ^1.1.2

  # UI
  google_fonts: ^8.0.1
  cupertino_icons: ^1.0.8
  lucide_icons: ^0.257.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/icon/mindspend.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icon/mindspend.png
  adaptive_icon_background: "#0A0B14"
  adaptive_icon_foreground: assets/icon/mindspend_foreground.png
  remove_alpha_ios: true
